### ISSUE TITLE
Implements draw base line in grid 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#156]
grid 안에서 base line 과  sub line 을 그림 

sub line 은 특정 간격을 좀 더 세밀하게 구분하,기 위해서 사용 .

예를 들어 

subline : [1, 1] 이라두 두면 

a - b 간격에  1줄 들어가고 
칸이 2개가 생기는데 

그 사이에 다시 한칸씩 나뉨    a, b 사이에 총 4칸이 됨 . 

callback 으로 설정 가능

**Comment by seogi1004** [comment]
이거 어찌 됨?

**Comment by seogi1004** [comment]
이거 그리드 개선하면서 필요없어진듯?

**Comment by easylogic** [comment]
이건 subline 그리는거라 기획을 해야함 

현재 있는 그리드는 그냥 기본 그리드고.
