### ISSUE TITLE
1.3.1에서 진행할 사항 논의 + 로드맵 정의

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#162]
일단 본 이슈에서 논의합시다.

**Comment by seogi1004** [comment]
1. 제니퍼에 있는 차트들의 기능을 구현하는 것
2. 유명한 차트 라이브러리 기능을 모두 구현하는 것

**Comment by easylogic** [comment]
2번은 너무 모호해 ~

**Comment by easylogic** [comment]
다른 차트 라이브러리들 중에 대쉬 보드만 구현하기

**Comment by seogi1004** [comment]
1. 기존의 SVG 아이콘을 차트에서 사용할 수 있는 방법 검토
2. 텍스트를 쉽게 추가할 수 있는 위젯에 대한 논의
3. 레전드 아이콘 정의 방법 논의

**Comment by easylogic** [comment]
2번에 대한 아이디어 

모든 axis, brush, widget 은 자신이 그려진 위치를 알 고 있다. 

x, y, width, height 를 특정한 함수나 속성으로 제공 

그럼 title 위젯은 그것에 맞춰서  

좌우, 위아래 선택해서 그린다.
