### ISSUE TITLE
typeCheck 안에 있는 체크 패턴을 개별 함수로 분리 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#172]
scatterpath  튜닝하면서 보고 있는데.. 

typeCheck 를 일단 어느정도 튜닝을 한 상태이긴 한데. 

Date 를 체크할려면 

if else 구분을 대략 6개 이상 거쳐서 가야함.  

모든 데이타가 date 라고 가정했을 때  이것도 부하가 어느정도 걸림 .. 

date 체크를 할 때마다 if 를 6번을 타고 가야해서리.. 
function 이랑 object 도 우선 순위가 뒤라서 마찬가지. 

그래서 

_.isArray
_.isDate
_.isObject

이런식으로 유틸리티 함수를 분리하는게 좋은 듯 하다. 

그러면 if else 거치지 않고 한방에  자료형 체크를 할 수 있으니. 

어떻게 생각함 ?

**Comment by seogi1004** [comment]
if else는 저번에 테스트했듯이 단순히 문자열 체크라서 그렇게 느리지 않을텐데...
정확한 자료를 주시오... 얼마나 차이가 나는지...

**Comment by easylogic** [comment]
date 그리드 때문에 그럼   i 가 Date 형인지 체크 해야하는데. 
여기서 소소하지만 루프를 많이 돌기 때문에 생기는 문제임. 

데이타가 작을 때는 거의 못느끼는 문제임.. 

그래서 따로 유틸성 메소드를 만드는게 어떻냐는 거지 . 

이건 예외 사항이라고 볼 수 있지.. 

데이타 50000 건씩 target 이 3개면  총 15만건에 대한 typeCheck 를 해야하는데 만만치가 않음 .

**Comment by easylogic** [comment]
그리고 이건 시간상의 체크 보다 전체 cpu 차지하는 비율에 대한 문제라. 

drawBrush 할 때 getXY 에서 date 그리드 가지고 오는 시간이 절반 이상 차지함. 

그래서 생기는 문제임.

**Comment by seogi1004** [comment]
그럼 저 부분만 date instanceof Date로 하는건 어떻소?

**Comment by easylogic** [comment]
일단 저 부분만 그렇게 바꿨음.  
그럼 전체적으로 규칙이 애매할까봐 함수를 만드는게 어떨까 하고 적은거임 .

**Comment by seogi1004** [comment]
성능의 문제가 되는 부분만 네이티브로 구현합세... 어쩔 수 없지;;

**Comment by easylogic** [comment]
그럼 특정 부분만 네이티브로 체크하는걸로
