### ISSUE TITLE
implements pattern 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#175]

**Comment by easylogic** [comment]
패턴 구현 했음. 

bar.html 샘플 보면 됨. 

chart.pattern.white 를 보면 

실제 pattern 을 어떤식으로 설정했는지 알 수 있음.

**Comment by easylogic** [comment]
기본적인 사용 방법은 색상이 들어가는 곳 모두 패턴 이름이 있으면 패턴으로 적용될꺼임.

**Comment by easylogic** [comment]
gradient 랑 거의 비슷한 형식으로 사용됨. 

color 에 이제 3가지가 들어가는거임

color
gradient
pattern

**Comment by seogi1004** [comment]
이거 이제 마무리된듯 하니... 클로즈함!
