### ISSUE TITLE
jui.js  주석 오타 수정 요청

### ISSUE THREAD

**Issue by 0929** [seogi1004/jui#185]
파일 : jui.js
라인 :16717 
내용 : // Max & Min 툴팁 생     -> // Max & Min 툴팁 생성    으로 수정 요청

**Comment by easylogic** [comment]
jui.js 는 빌드하면 나오는거라 

실제 원본 파일에서 고치면 됨.

**Comment by seogi1004** [comment]
수정 완료요!!
