### ISSUE TITLE
Add 'accordion' css & script components

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#187]
사용자정의대시보드에 들어가야 할 아코디언 컴포넌트입니다. 
두가지 타입과, 각 타입별 두가지의 사이즈가 있습니다. 
첨부한 디자인 가이드를 참고하여 작업해주시기 바랍니다.

**Comment by easylogic** [comment]
예제에 정의되어 있느 이벤트 ,  이거 화살표 방향 바꾸는거지? 

흠 이건 기본적으로 지원해줘도  될 것 같은데. 

매번 화살표를 바꾸는건 ㅋㅋ 조금 애매할 듯 하다. 

event: {
+                open: function(index, e) {
+                    $(this.root).find("i").attr("class", "icon-arrow1");
+                    $(e.target).find("i").attr("class", "icon-arrow3");
+                }
+            },
