### ISSUE TITLE
차트 키셋 설정 옵션 추가

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#191]
데이터의 프로퍼티 키가 고정인 브러쉬가 있다.
candlestick, topology.node, full-gauge

관련해서 옵션을 통해 키를 변경할 수 있는데, 이 부분은 빌더에서 옵션으로 설정할 수 있으면 좋을듯...

**Comment by easylogic** [comment]
브러쉬 마다 다 다를텐데 어떻게 설정하는거임 ?

**Comment by seogi1004** [comment]
엑시스에 keymap이라는 옵션을 넣었음...
데이터 키를 고정으로 쓰는 경우가 많은데, 데이터를 재가공 할 필요없이 옵션 제공으로 두번 작업을 방지하기 위함...
그리고 불필요한 브러쉬 옵션을 제거할 수 있음

**Comment by easylogic** [comment]
불필요한 브러쉬 옵션을 제거는 할 수 있지만 

실제로 브러쉬마다 다른 특성을 가질 수 있는 필드들인데  

저렇게 axis 에 넣는게 맞는 일인가? 

브러쉬의 특징인데 말이지. 

이건 생각해봐야함.

**Comment by easylogic** [comment]
keymap 설정은 브러쉬로 올립니다. 

관련 코드는 수정되면 develop 에 푸쉬할게요.

**Comment by seogi1004** [comment]
관련해서 수정할 코드는 아래와 같습니다.
수정하실 때, 모두 같이 수정해주세요.

topology.node, fullgauge, ohlc, candlestick

**Comment by seogi1004** [comment]
그리고 관련 메뉴얼도 수정해야함

**Comment by easylogic** [comment]
axis 에 keymap 설정으로 변경 ,
