### ISSUE TITLE
nodejs 버전 만들기 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#198]
jui 를 nodejs 에서 쓰게 하자는 목표임 

서버에서도 jui 기법을 사용해서 그대로 차트를 그릴 수 있음. 

즉 js 용 버전을 따로 안 만들어도됨. 

```
npm install jui

var jui = require('jui');

var chart = jui.create("chart.builder", $("<div></div>"), { 
   ..
   // options 

});

// xml 로 차트 출력 
console.log(chart.svg.toXml());

```

**Comment by easylogic** [comment]
nodejs 에서 jui 의 모든 기법을 사용할 수 있음. 

jui,define 부터 시작해서 

jui 가 가지고 있던 기본 구조를 가지고 서버쪽 코드를 작업하는거지 

클라도 되고 서버도 되고 ㅡㅡ; 

구조만 잘 맞추면  동일한 코드를 가지고 서버 클라 다 한방에 ~

**Comment by easylogic** [comment]
차트 서버 렌더링 된다고 홍보도 할 수 있음.

**Comment by easylogic** [comment]
관련 코드는 f3229bf7e5325e3c70b6ad5eeccf9ce6b2f3036c 여기 참조

**Comment by seogi1004** [comment]
ㄷㄷㄷ 별도의 코드 변경 없이 바로 가능하면 대박인듯...
나 떨고 있음 ㄷㄷㄷ

**Comment by seogi1004** [comment]
이거 브랜치이름 nodejs로 바꿔주셈~
단순히 node라고하니 뭔가했음~

**Comment by easylogic** [comment]
합치면 지울거라 일단 그대로 두겠음. 브랜치는 

몇개 테스트를 더 해보고  최종 코드 합치고 말해주겠음.

**Comment by easylogic** [comment]
1. 빌드 오류 없음  - yes 
2. grunt test  했을 때 모두 ok 확인 - yes
3. sample 에 있는 html 파일 브라우저에서 실행 되는지 확인 - yes

 다 되는 것 같으다. 

npm publish 에 대해서 알아봐야겠다.

**Comment by easylogic** [comment]
일단 node 브랜치는 머지함.

**Comment by easylogic** [comment]
난감한 상황이 발생. 

npm 이 version 에 4자리수를 지원하지 않음 ㅡㅡ; 

1.3.1  

형태만 지원함.. 

그래서 npm publish  명령을 날릴 수가 없음.. 

저걸 해야 npm install 해서 쓸 수 있는데.. 

버전 코드를 바꿔야 할 듯 한데.. 

어떻게 생각함 ?

**Comment by easylogic** [comment]
npm install jui 

적용함.
