### ISSUE TITLE
엑시스 및 차트의 패딩 관련 이슈

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#200]
1. 그리드는 padding의 영향을 받지 않으므로 대쉬보드 구성시 에로사항이 있음
2. 엑시스는 x, y가 기본 0이고, 차트의 x, y는 패딩의 영향을 받는데, 위젯 구현시 문제가 좀 있음

관련해서 의논이 필요함. 대쉬보드 구성하다보니 문제가 좀 있음...

**Comment by easylogic** [comment]
흠 axis 에 패딩까지 적용할려면 졸라 복잡한데 


대쉬보드 같은 경우는 

axis 는 area 를 잘 정의하는걸로 하면 좋지 않을까? 
area 자체로 그 차트의 크기를 정하는거라. 

예를 들어  width 50% 를 두개 두는게 아니라 

width : 40% 를 두개를 두고  x 를 50% 로 뛰우면  일단은 공간 확보는 되거든. 

그리구 위젯 같은 경우는 

axis.area.x , y 를 더해서 위젯에서 처리 하면 될 듯 한데. 

고민 좀 해봐야할듯

**Comment by easylogic** [comment]
axis 에 padding 추가 했음.
