### ISSUE TITLE
템플릿 코드 모듈화 하기 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#209]
grunt 로 템플릿 엔진을 모듈화 해서 탑재한다. 

기본 템플릿 엔진을 탑재하는 것이기 때문에.. 

유저들은 따로 템플릿을 등록하지 않고 기본 UI 를 사용할 수 있다.

**Comment by seogi1004** [comment]
맵을 먼저합시다. ㅎㅎ

**Comment by seogi1004** [comment]
이건 어케하기로 햇지?

**Comment by easylogic** [comment]
담에 필요하면 넣고 일단 닫음.
