### ISSUE TITLE
Research and development to 3D charts

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#212]
진행 순서는 다음과 같음...

* 그리드 구현
* 브러쉬 구현 (바, 컬럼)

**Comment by seogi1004** [comment]
스케일을 어떻게 구현해야할지 고민이 필요함!

**Comment by seogi1004** [comment]
생각해보니 3D는 x축은 bottom, y축은 left로 고정해야 함...
오히려 심플해졌음...

**Comment by seogi1004** [comment]
이번 기회에 RGB 코드 변경하는 함수를 추가하면 좋겠음...
왜냐하면 3d 브러쉬 같은 경우... 측면은 보통 어둡게해서 사용해서;;
color 메소드에 관련 기능이 있으면 좋을 것 같음...

**Comment by easylogic** [comment]
util.color 에   lighten, darken 두가지 메소드 추가 되었음. 

color.lighten(rgb, 0.5)  하면 0.5 비율만큼 밝아지고 

color.darken(rgb, 0.5) 하면 0.5 비율만큼 어두워짐

참고하삼.

**Comment by easylogic** [comment]
http://api.jui.io/#!/api/util.color

**Comment by seogi1004** [comment]
올 멋쟁이!!!! 3d 그리드 한번봐보셈~
옵션에 depth랑 angle 변경해봐~ ㅋㅋ

**Comment by seogi1004** [comment]
x,y,z 축은 고정으로하고, x와 y는 기존처럼 자유롭게 쓸 수 있게 해야함...
꼼수로 그리드는 기존 그리드를 건들이지 않고 그렸는데...

브러쉬를 그리기 위해 scale 함수를 각각의 그리드 별로 고쳐야할 듯...
생각보다 어렵군... ㅜㅜ

그렇다고 x는 블럭, y는 레인지로 고정하는건 우리 컨셉상 맞지 않아서...
ㅠㅠ

**Comment by easylogic** [comment]
그러지 말고 svg 자체 속성만 가지고 그리삼 

어자피 선만 그으면 되는거니깐 .

이미 x, y 에 있는 element 들이 다 절대 위치값을 가지고 있음 

그것만 가지고 와서 그려도 됨 . 

너무 복잡하게 가지마 

이건 scale 을 해서 해결하면 졸라 복잡함. 

그리기에 집중하면 졸라 심플할 수도있음.

**Comment by easylogic** [comment]
구조상 안되겠군 ㅡㅡ; 

공통 인터페이스를 따로 만들어야할 듯

**Comment by seogi1004** [comment]
depth와 angle에 따라 줄어든 x,y축 길이만큼만 스케일에서 보정해주면 되는데...
으음... =ㅁ= 왜 안맞는거 같지!?

**Comment by seogi1004** [comment]
일단 12개 브러쉬 추가한걸로 해당 이슈는 마무리하겠음...
힘들었음 ㅠㅠ
