### ISSUE TITLE
단일 목록에 대한 차트 표현 이슈

### ISSUE THREAD

**Issue by lsj4401** [seogi1004/jui#213]
series : {
            ie : { text : "IE" },
        },
        axis : {
            data : [
                { ie : 100}
            ]
        },
        brush : {
            type : "pie",
            showText : true
        },
차트 이용시 다음과같이 목록이 하나있을경우 100% 채워진 차트가 아닌 0으로 채워진 차트가 보입니다.

**Comment by easylogic** [comment]
전체 크기로 나와야 하는 부분이 path 형태로 그릴 수가 없었네요. 

그래서 circle 형태로 그렸어요. 

develop 브랜치에서 확인 해보시면 됩니다.
