### ISSUE TITLE
Implements Map Charts

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#214]
map 차트가 필요한 시점이 온 것 같다. 

map 차트를 하기 위해서는 몇가지가 필요하다. 

1. 위치 설정하기 
2. 맵 그리기 (svg 맵이 필요하다.) 
3. 맵 자체가 차트이긴 하지만 맵의 위치마다 서브 차트가 들어 갈 수 있다. 
4. 지역 매칭에 대한 기준이 필요하다. 
5. 일단은 세계 지도 하나랑 한국 지도를 기준으로 처리한다.

**Comment by easylogic** [comment]
각각의 지도는 grid 로 그리고 개별 기능은 brush 로 채운다.

**Comment by easylogic** [comment]
지도는 svg 파일 또는 google map, naver, daum 등등의 맵도 지원 할 수 있게 

위도 경도 시스템과 지역별 영역 시스템 모두 구현한다.

**Comment by easylogic** [comment]
해당 위치의 이름을 key 로 지정하고 

map svg 는 key 에 대한 정보도 가지고 있다.

**Comment by easylogic** [comment]
```javascript
this.axis.c(region);;
```

하면 아래의 코드를 리턴해준다. 

```javascript
{ 
    el : path element,
    x : start x point ,
    y : start y point,
   width : path's width,
   height : path's height
}
```

그러면 path 를 이용해 브러쉬는 몇가지 작업을 할 수 있다. 

1. 색상을 변경한다. 
2. 영역 위에 차트를 생성한다. 
3. clone 해서 자신만의 색상을 칠한다.

**Comment by easylogic** [comment]
실제 svg 코드로 되어 있는 맵을 어떻게 하면 쉽게 정의 할 수 있을까?

**Comment by seogi1004** [comment]
맵 차트라는 말을 좀 더 넓은 의미의 말로 바꿔야 할듯!
우리의 가장 강력한 기능이 될 수 있음...

**Comment by easylogic** [comment]
정적인 맵 표현. 

map 은 grid 의 한 종류로서 표현 

나머지는 브러쉬로 구현 하는 방식. 

현재는 샘플. 

실제 예제를 만들어야함.

**Comment by seogi1004** [comment]
일단 요하가 위치 잡아준거 적용했고, 조금 코드를 수정했음...
적용하면서 느낀 점을 말해보겠음...

* 기본 스타일 defs에 있는걸 로드해서 적용해줘야할 것 같음
* mapBase, map 하나로 통합하면 좋을 것 같음 (이름 변경 path)
* map/world.js와 같은 모듈을 안만드는게 좋을 듯 싶음...
* svg는 로드를 하고 기본 패스 생성 및 스타일, 속성 정의만해주면 되고 나머지는 브러쉬와 위젯을 통해 그리는게 좋을 듯... 애초에 다른 맵과는 좀 더 자유도를 주는게 목적이니...

**Comment by seogi1004** [comment]
그리고 대충 테스트해보면서 느낀건데, 빌더 그대로 사용한것 레알 신의 한수인듯...

**Comment by seogi1004** [comment]
일단 기본 틀이 잡혔으니 본 이슈는 클로즈하겠음...
