### ISSUE TITLE
request implements of using user-defined images in chart

### ISSUE THREAD

**Issue by SangsPark** [seogi1004/jui#217]
chart brush 에서 type : 'scatter' 등의 경우 symbol 에 'triangle', 'circle' 등의 옵션을 사용하는 것외에 사용자가 지정한 이미지를 이용할 수 있으면 좋겠습니다.

**Comment by seogi1004** [comment]
다음 버전에 관련 기능 추가할게요!

**Comment by SangsPark** [comment]
피드백을 엄청 빨리 주시네요.
감사합니다.

**Comment by seogi1004** [comment]
관련 기능 추가되었습니다.
sample/chart/scatter_image.html 샘플을 보시면 됩니다.

**Comment by SangsPark** [comment]
소스상 라이브러리 버전 차이는 없지만,  라이브러리는 새로 받아야 되는 부분이겠죠?

**Comment by seogi1004** [comment]
한 시간 전에 1.3.3 버전 릴리즈 했습니다.
릴리즈 되지 않더라도 develop 브랜치에는 항상 업데이트가 되니 이 점 참고해주세요. ^^;
