### ISSUE TITLE
ui theme 지원하기

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#219]
less 에서 고정적으로 사용되는 변수를 빼서 

모듈화 한 다음 재구성할 수 있는 api 를 만들어야할 듯. 

사이트에서 테마를 바꿀 수 있도록 지원하면 좋을 듯

**Comment by seogi1004** [comment]
이거 안하기로 하지 않았음?

**Comment by seogi1004** [comment]
=ㅁ= 일단 클로즈함!
