### ISSUE TITLE
jui sample 페이지 제공하기 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#220]
jui 를 활용한 실제 sample 페이지를 만들어서 보여줌. 

단순 ui 만 봤을 때랑 실제 전체 예제페이지를 봤을 때랑은 느낌이 다름. 

실제 페이지를 가져다가 쓸 수도 있고. 

현재는 admintool 샘플 하나 제작중 . 

http://seogi1004.github.io/jui/en/example/admintool/

**Comment by easylogic** [comment]
어떤 샘플을 만들 것인가? 

하나씩 추가해보자. 

https://docs.kentico.com/download/attachments/40174385/Application_dashboard.png?version=1&modificationDate=1392282145368&api=v2

**Comment by easylogic** [comment]
http://www.onextrapixel.com/2014/03/06/30-vivid-dashboard-ui-designs-for-your-inspiration/

여기 예제들은 느낌이 다르네.

**Comment by easylogic** [comment]
차량용 대쉬보드 같은 것도 만들 수 있을까? 

http://www.librow.com/content/common/images/products/product-3/car-lcd-dashboard-1.gif

http://ak.picdn.net/shutterstock/videos/2395157/preview/stock-footage-car-dashboard.jpg

**Comment by easylogic** [comment]
https://s-media-cache-ak0.pinimg.com/736x/b2/9c/a9/b29ca96e67856186367d372511b348b3.jpg

이런것도 쉽게 만들 수 있어야한다.

**Comment by easylogic** [comment]
http://cdn6.psdtex.com/static/2013/6/26/simple-registration-login-form-psd.jpg

폼 요소에 대한 예제도 필요하다.

**Comment by seogi1004** [comment]
ui 플레이가 추가되었으므로 이슈 클로즈!
