### ISSUE TITLE
webjars 등록

### ISSUE THREAD

**Issue by millky** [seogi1004/jui#226]
안녕하세요 ^^ 우선 좋은 UI를 공유해 주셔서 감사합니다.
주로 자바 서버쪽 개발하는 입장에서 Gradle나 maven으로 빌드시 webjars 사용하면 간단하게 war에 포함할 수 있어서 많이 사용중입니다.
http://www.webjars.org/ 등록되어 있으면 좋을 것 같습니다.
감사합니다.

**Comment by easylogic** [comment]
관심가져주셔서 감사합니다. 
webjars 에 request 등록하였습니다. 

처리 되는 대로 다시 알려드릴게요. ^^

**Comment by easylogic** [comment]
```
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>jui</artifactId>
			<version>1.3.3</version>
		</dependency>
```

적용되었습니다. 

maven 에서 dependency 설정 하시면 되요. 

앞으로 버전업 될때마다 webjars 도 같이 반영하겠습니다.

**Comment by easylogic** [comment]
다시 오픈 합니다. 

jquery 디펜던시가 걸려있는데.  

이 버전이 webjars 에 없네요. 

jquery 버전을 수정하고 다시 봐야할 것 같습니다.

**Comment by millky** [comment]
bower 로 추가하는 부분이 생겼고 (http://www.webjars.org/bower) 이미 추가되어 있네요!!

```
<dependency>
    <groupId>org.webjars.bower</groupId>
    <artifactId>jui</artifactId>
    <version>1.3.3</version>
</dependency>
```

```
compile 'org.webjars.bower:jui:1.3.3'
```

감사합니다 ^^

**Comment by millky** [comment]
http://search.maven.org/#artifactdetails%7Corg.webjars.bower%7Cjui%7C1.3.3%7Cjar
