### ISSUE TITLE
Add options in area & line brushes

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#228]
1. 현재는 라인 브러쉬와 함께 사용하는데, 별도로 그려볼까 생각 중...
2. 마우스 오버시 해당 인덱스의 타겟에 이벤트 발생하게 구현 (현재는 타겟만 됨)

**Comment by seogi1004** [comment]
일단 area 브러쉬에 line이란 옵션을 추가했음...
아무래도 있으면 좋ㅇ르것 같음...

**Comment by easylogic** [comment]
이건 두개 원래 조합해서 쓰는게 원칙이지 않음 ?

**Comment by seogi1004** [comment]
line은 그대로 두고, scatter에 hide라는 옵션을 추가했음...
line+scatter hide로 사용하면 마우스 오버시 스카터가 보이는 효과가 나타남...
line에서 툴팁 사용할 때의 불편함을 해결할 수 있음...
