### ISSUE TITLE
위젯에서 브러쉬를 그릴 수 있는 코어 API 개발

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#232]
스케일 유틸과 기본적인 데이터 핸들링 메소드를 상위 모듈인 draw로 올리고...
위젯 코어에 관련된 API를 추가하면 될듯?

**Comment by easylogic** [comment]
이걸 왜 하는거임 ? 

참고로 svg 안에 svg 가 들어감 

즉, chart.builder 를 widget 에서 생성하면 됨. 

굳이 api 가 있을 필요가 없음.

**Comment by seogi1004** [comment]
내일 테스트 해볼겨!

**Comment by seogi1004** [comment]
일단 zoomscroll 위젯과 토폴로지 노드를 더블클릭하면 차트를 노드에 보여줄 수 있는 nodeChart 옵션을 추가하였음...
