### ISSUE TITLE
그리드의 extend 옵션, 엑시스로 변경

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#234]
keymap이나 data, buffer, area 등... 중복적으로 사용되는 경우가 많음...
그래서 그리드의 extend를 엑시스로 변경하겠음...

**Comment by seogi1004** [comment]
일단 샘플만 수정해서 반영했고, 차트 플레이에도 적용해야 함...
매우 중요한 이슈임!!!

**Comment by easylogic** [comment]
괜찮은 듯, 화이팅 ~!

**Comment by seogi1004** [comment]
메뉴얼도 수정했음~ 한번 봐주셈!!
