### ISSUE TITLE
table editCell 에서 editend이벤트가 계속 호출됩니다

### ISSUE THREAD

**Issue by SilverAndLight** [seogi1004/jui#242]
안녕하세요~
 table을 사용하는 중 editCell을 사용할 때 문제가 발생합니다.
 셀의 값 수정한뒤 혹은 다른 Row를 선택하게되면 editend이벤트가 계속 호출됨.

![editcell](https://cloud.githubusercontent.com/assets/11657460/6839379/d0dc026e-d3aa-11e4-9889-1e22795c40b7.png)

![script](https://cloud.githubusercontent.com/assets/11657460/6839475/45357e46-d3ac-11e4-9ff2-96505d7d306f.png)

![html](https://cloud.githubusercontent.com/assets/11657460/6839479/4c757ab2-d3ac-11e4-8d48-b111609d7749.png)

**Comment by seogi1004** [comment]
확인 해보겠습니다!!!

**Comment by SilverAndLight** [comment]
우선 JUI 라이브러리 정말 잘 사용하고 잇습니다. 
바쁘실텐데 한가지만 여쭙겠습니다..
Tree와 Table을 동시에 사용할경우 템플릿을 각각 적용하는 방법이 혹시 있나요?

Table을 사용할때 jui.setup에서 템플릿 문법을 적용하는데  이문법이 tree의 템플릿 문법에도 적용되어
tree의 tpl 옵션을 사용해도 트리가 정상적으로 보이지 않습니다.

-----------------------------------------------------------
jui.setup({
template: {
 evaluate : /<\?([\s\S]+?)\?>/g,
 interpolate : /<\?=([\s\S]+?)\?>/g, 
 escape : /<\?-([\s\S]+?)\?>/g
},
logUrl: "/jui/tool/debug.html"
});
-----------------------------------------------------------
jui.ready([ "uix.tree" ], function(treeFunc) {
    tree = treeFunc(".tree_1", {
 tpl: {
        	node: $("#tpl_tree").html();
        }
}
});
-----------------------------------------------------------

**Comment by easylogic** [comment]
jui 에서 템플릿 문법은 전체 공통으로 사용하는 것이기 때문에 현재는 분리해서 사용할 수가 없습니다. 
향후에는 여러 템플릿엔진들과 연동할 수 있도록 구성할 예정입니다.

**Comment by SilverAndLight** [comment]
일단은 트리와 테이블을 각각 만들어서 iframe을 통해 한 화면에 출력하여 해결했습니다.

빠른답변 감사합니다

**Comment by seogi1004** [comment]
테이블 버그 수정되었습니다!

**Comment by SilverAndLight** [comment]
editend이벤트가 계속 호출되는 문제가 해결되었습니다. 
cell 값 수정후 다른 로우에 클릭하게되면 값이 변경되는 이벤트에서 몇몇 문제가 발생합니다.

table.js

// 포커스가 바뀌었을 경우 업데이트
			self.addEvent($obj.tbody.find("tr"), "click", function(e) {
				if(e.target.tagName == "TD" || e.target.tagName == "TR") {
					update(e);
				}
			});
			
기존의 row엘리먼트에 잡혀있던 click이벤트와 TR엘리먼트에 잡은 click 이벤트 사이에 충돌이 일어나는 것 같습니다.

궁여지책으로

$obj.tbody.find("tr").one("click", function(e) {
				if(e.target.tagName == "TD" || e.target.tagName == "TR") {
					update(e);
				}
			});

이렇게 수정하여 사용하고있습니다.
정확한 이벤트제어를 하고싶은데 on, off로 해봤는데 잘모르겠네요..ㅜㅜ
