### ISSUE TITLE
IE9/10 script error

### ISSUE THREAD

**Issue by RyuUser** [seogi1004/jui#251]
IE9/IE10 에서 차트의 sample html 열었을 때 발생하는 스크립트 오류 입니다.
모든 차트에서 발생하는건 아니고 일부 차트에서 발생됩니다.

![1](https://cloud.githubusercontent.com/assets/11845502/7037457/13b1d324-ddde-11e4-9a78-b7c7847020b8.JPG)

일부 차트에서는 아래와 같은 스크립트 오류도가 발생합니다.

![2](https://cloud.githubusercontent.com/assets/11845502/7037459/1aa04d6e-ddde-11e4-9476-6d2061847b96.JPG)

**Comment by seogi1004** [comment]
문제 확인하였습니다.
수정 후 알려드리도록 하겠습니다!

**Comment by seogi1004** [comment]
해결되었습니다. 크리티컬한 이슈는 아니여서 핫픽스 릴리즈는 하지 않았습니다.
그냥 develop 브랜치 다운로드 받으시면 됩니다. ^^

**Comment by RyuUser** [comment]
넵~ 받아서 확인해보겠습니다~ 감사합니다~~~
