### ISSUE TITLE
[JUI] Basic Bar Chart 사용 시에 그래프 상에 '값' 표기가 되지 않는 점.

### ISSUE THREAD

**Issue by jinammin** [seogi1004/jui#253]
안녕하십니까. JUI를 사용해서 웹 서비스를 개발하고 있는 사용자입니다.
Basic Bar Chart 사용 시에 그래프 상에 '값' 표기가 되지 않는 점에 대한 추가 개발 부탁드립니다.
즉, Full Stacked Bar Chart의 "showText : true"처럼 그래프 상에서 값 자체를 보고 싶습니다.
이러한 기능이 개발된다면, 그래프를 인쇄하여 배포할 때 이를 읽는 사람의 가시성이 크게 높아지리라 생각됩니다.

감사합니다.

**Comment by easylogic** [comment]
관심 가져주셔서 감사합니다. 

처리 되는 대로 다시 알려드리겠습니다.

**Comment by seogi1004** [comment]
display 옵션에 all을 주면 전체 텍스트가 나옵니다!
관련해서는 별도로 릴리즈 하지 않았으니 develop 브랜치 다시 받으시면 됩니다!

**Comment by moon-sooyun** [comment]
display 옵션에 all을 줬을 때 점 빼고 텍스트만 나오게 할 수는 없나요?

**Comment by moon-sooyun** [comment]
display 옵션에 all을 줬을 때 점 빼고 텍스트만 나오게 할 수는 없나요?
