### ISSUE TITLE
[Zoom기능] zoom 영역의 데이터 정보 담기

### ISSUE THREAD

**Issue by choisee** [seogi1004/jui#259]
zoom end시점에 zoom 영역 내 data 정보를 가져오고 싶습니다.
현재 api를 찾아봐도 나와 있지 않아 이슈 등록합니다...

**Comment by easylogic** [comment]
zoom이 완료되면 현재 시점으로 data 를 설정 합니다. 

brush 나 위젯에서 

this.axis.data 로 가지고 오면 현재 표현 시점의 데이타가 됩니다. 

chart 그릴 때 실행된 전체 데이타를 가지고 오고 싶으시면 this.axis.originData 로 가지고 오시면 됩니다.

**Comment by easylogic** [comment]
외부 에서 data 를 가지고 오고 싶으시면 

```javascript 
chart.axis(0).data 
```

로 가지고 오시면 됩니다.
