### ISSUE TITLE
[Map] 맵 브러쉬 절대 좌표로 구현되게 수정

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#263]
기존에는 맵의 하위 엘리먼트로 브러쉬가 존재했으나...
그렇게 되면 맵의 scale을 무조건 따라야 하므로 문제가 있음...
그래서 브러쉬는 절대 좌표를 받을 수 있어야 함...

**Comment by seogi1004** [comment]
맵 크기와 위치를 변경시 매번 업데이트 하므로 캐싱 방법을 고민해봐야 함...

**Comment by easylogic** [comment]
맵 파일 캐슁이 이해가 안감. 

맵의 크기와 위치가 변경 되는데 이게 캐슁이 가능함 ? 

어짜피 우리는 조각조각 낸 맵이 아니라 전체 path 로 그린 맵인데 

scale 별로 캐슁하는게 의미가 있나?
