### ISSUE TITLE
차트 Y축 value와 step을 적절한 개수, 적절한 값으로 표현하기

### ISSUE THREAD

**Issue by kaidu1982** [seogi1004/jui#267]
차트의 maxValue와 Y축 높이 사이즈를 계산하여 반영하기. -> 홍재석님이 여기에 적으라고 하였음 ㅎ

**Comment by seogi1004** [comment]
진호형 이거 해줘용~~~ 오토로~~ 쉽게 쓸수있게!!!
그리고 x축 그리드 라인이 연한데?

**Comment by easylogic** [comment]
x 축 그리드 라인이 연한건 아니고 ㅡㅡ; 두줄이 그려져서 그럼.

**Comment by seogi1004** [comment]
@easylogic 이거 해줘~~용~

**Comment by easylogic** [comment]
규칙을 정해야겠군. 

* nice 형태의 숫치를 정확히 계산한다. (min,max 구하기)
* 구해진 min, max 에서 높이에 따른 unit 간격을 구한다. 
* unit 간격으로 step 개수를 구한다

**Comment by seogi1004** [comment]
@easylogic 이거 어케하기로 했음?

**Comment by easylogic** [comment]
이건 사이즈에 대한 명확한 기준이 없어서 생각을 좀 해야함.

**Comment by easylogic** [comment]
내부적으로 range 그리드의 많은 변화가 있었습니다. 

숫치는 자동으로 계산되겠끔 구조화 잡혀 있습니다. 

최신 버전의 JUI 를 다운로드 해주세요.
