### ISSUE TITLE
downloadImage 메소드가 실행이 안됨 (SVG 유틸)

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#269]
캔버스로 바꿔서 어떻게 하는거 같은데...
이 부분이 문제인듯? 한번 봐주셈

**Comment by seogi1004** [comment]
이거 빨리 고쳐주셈

**Comment by easylogic** [comment]
https://github.com/seogi1004/jui/commit/03eb1850acb2565a2169412d70447f0a77a0cc61#diff-f10f3cbacb92b8368322e0c6233ce9bd

이거 이름 잘 못 수정 했는디? 이걸 왜 바꾼거임 ? 

canvas.toDataURL 은  캔버스 함수라 바꾸면 안되는디 ㅡㅡ;  toDataURI 로 들어가있네.

**Comment by easylogic** [comment]
참고로 brush 에 animate : true 옵션이 있으면  브러쉬 안 그려짐. 

이유는 로드 하자 마자 png 로 만들기 때문임. 

만약 그걸 다 감안하고 그릴려면 아마도 딜레이를 따로 줘야할듯 .
