### ISSUE TITLE
[Table] row click 이벤트 시에 col.index 확인법 좀 

### ISSUE THREAD

**Issue by yuhwkim** [seogi1004/jui#270]
jui.ready([ "util.base", "ui.dropdown", "uix.table" ], function(_, dropdown, table) {
			tableT = table("#table_overview", {
				data : odata,
				resize : true,
				event: {
					click: function(row, cell){
						alert(cell.index);
					}
				},
				animate : true
			});
		});

간단합니다. row.index 는 잘 되지만, column.index는 되지 않더군요. 여러 시도를 해봤지만 안됩니다. 

click 이벤트 시에 컬럼 index를 확인할 수 없습니까? 
colclick 은 사용해봤습니다. 테이블 타이틀인 컬럼을 선택하면 index 확인이 되더군요. 
제가 알고자 하는 것은 row 안에 있는 컬럼을 선택했을 때, 그 값을 확인하는 방법입니다. 

부탁드립니다.

**Comment by easylogic** [comment]
현재 cellIndex 는 td 객체의 속성으로 되어 있습니다. 
그래서 아래와 같이 얻어올 수 있어요. 

```javascript 
        event: {
            click : function(row, e) {   // row 를 클릭 할 때 
              console.log(row.index);   // row.index 
              console.log(e.target.cellIndex);   // column index 
            },
        }
```

**Comment by yuhwkim** [comment]
그렇군요 ! 감사합니다.

**Comment by kiizoo** [comment]
저도 궁금했던 부분입니다
조언 감사합니다
