### ISSUE TITLE
Marker 맵 브러쉬 개발

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#271]
커스텀 마크업 임포트하는 브러쉬 개발
 - foreignObject 엘리먼트가 IE에서만 안됨 ㅠㅠ
 - 그래서 IE의 경우 MARKUP이아닌 SVG 리턴하는 형태로 해야할듯
 - 그리고 JUI TPL을 사용할 수 있게 해야겠음

**Comment by easylogic** [comment]
:+1:
