### ISSUE TITLE
legend filter 값이 true시 발생하는 문제?

### ISSUE THREAD

**Issue by hhgyu** [seogi1004/jui#273]
seogi1004.github.io/jui/res/chartplay/index.html#fullstack.js

legend에서 중간에 하나를 선택 해제시
legend 컬러와 막대 차트의 컬러가 일치 하지 않습니다.

예제 차트에서 LG 선택 해제시 아래와 같이 나옵니다.

![default](https://cloud.githubusercontent.com/assets/4644504/7783676/9fd98ec2-0184-11e5-86eb-c67cdeb70ae7.PNG)

**Comment by hhgyu** [comment]
예제에서는 제대로 나오네요...

![default](https://cloud.githubusercontent.com/assets/4644504/7783687/5c188f48-0185-11e5-9dd9-d0fb31cdd577.PNG)
위에 차트에서 DNS오류(노란색)를 선택해제시 아래와 같이 나옵니다.
![2](https://cloud.githubusercontent.com/assets/4644504/7783688/5c1a6192-0185-11e5-9de5-dee5cb7ff9c9.PNG)

**Comment by hhgyu** [comment]
series 옵션이 정의가 안되어 있을때 이런 문제가 발생합니다.

**Comment by easylogic** [comment]
@hhgyu  이슈 감사합니다. 확인해보고 답변드릴게요.

**Comment by easylogic** [comment]
legend 에서 brush 에 그릴 때 color 코드를 맞춰주질 않아서 생기는문제였네요. 
수정되었습니다. 개발 브랜치에서 확인 하시면 됩니다.
