### ISSUE TITLE
legend filter 값이 true시 발생하는 문제? 2

### ISSUE THREAD

**Issue by hhgyu** [seogi1004/jui#274]
![default](https://cloud.githubusercontent.com/assets/4644504/7783985/8ef6f46c-0190-11e5-9347-46e39f64a7be.PNG)
![2](https://cloud.githubusercontent.com/assets/4644504/7783986/8f1dabc0-0190-11e5-9c0f-80636fe6ebe6.PNG)

tooltip all 이 true 일이면서
legend filter 이 true
두번째 처럼
tooltip이 제대로 표시가 안됩니다.

**Comment by seogi1004** [comment]
답변이 늦어서 죄송합니다.
예전에 위젯 코어 리펙토링하면서 실수로 몇가지 메소드를 제거했었네요.

아래 샘플 확인해주세요.
http://seogi1004.github.io/jui/res/chartplay/index.html#stack_area.js

참고로 다음 릴리즈 전에 반영하시려면 develop 브랜치를 다운로드 받아주세요.
