### ISSUE TITLE
[JUI] Pie Chart: 수치를 기준으로 오름차순/내림차순 정렬할 수 있는 기능과 비율 표시(%)가 가능하게끔 업데이트 요청드립니다.

### ISSUE THREAD

**Issue by jinammin** [seogi1004/jui#275]
Pie Chart: 수치를 기준으로 오름차순/내림차순 정렬할 수 있는 기능과 비율 표시(%)가 가능하게끔 업데이트 요청드립니다.

이러한 기능이 개발된다면 파이 차트의 활용도가 더 좋아질 것이라 생각합니다.

**Comment by easylogic** [comment]
현재 데이타에 대한 정렬은 브러쉬별로 제공하고 있지 않습니다. 
이 부분은 외부에서 직접 해주셔야 할 것 같아요. 

비율 표시 부분은 brush 에 format 함수를 재정의 하면 되는데 코드를 보니깐 max 에 대한 값을 넘겨주지 않아서 바로 구현을 할 수가 없네요. 

이 부분은 코드 반영해놓겠습니다.

**Comment by jinammin** [comment]
답변 감사합니다.

정렬은 제가 직접하되, % 표시는 차후에 개발 해두시겠다는 것이지요?
그렇다면 대략 몇주 이내에 사용이 가능할지 말씀해주실 수 있으신가요?

**Comment by easylogic** [comment]
코드 적용 하였습니다. 

develop 브랜치 다운로드 받으셔서 

sample. 코드에  pie.html 보시면 확인 하실 수 있습니다.

**Comment by jinammin** [comment]
괄호 안에 NaN% 라고 나오던데, 여기서 어떻게 해야 정상적으로 비율을 볼 수 있을지요?
                format : function(k, v, max) {
                    return this.icon("check") + k + ": " + v + "(" + ((v/max)*100).toFixed(2) + "%)";
                }

**Comment by jinammin** [comment]
max 값을 직접 구해서 대입하여 해결했습니다.
빠른 조치에 감사드립니다!

**Comment by seogi1004** [comment]
해결되었으니 이슈 닫겠습니다.
