### ISSUE TITLE
데이타 순서별 커스텀 색상 구현하기 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#279]
현재는 brush 에서 색상을 target 순서별로 하고 있습니다. 

각 데이타 순서대로 다른 색상을 지정할 수 있어야 할  것 같습니다. 

아니면 데이타에 따른 색상 가충치를 적용할 수 있어야 할 것 같아요. 

아래는 샘플 코드 입니다. 

```javascript
brush : {
    type : 'bar',
    colors : function(index, value, targetIndex) {
        if (value < 50) return '#ff0000'; 
        if (value < 100) return '#ffff00';
    }
}
```

관련 이슈 #278

**Comment by jinammin** [comment]
이 기능이 제공된다면 정말 유용하리라 생각합니다! ^^

**Comment by seogi1004** [comment]
@easylogic 막상 구현하려고보니 브러쉬의 this.color에 targetIndex만 넘기네...
이거 구현하려면 전체 브러쉬 다 고쳐야됨...
그냥 스카터랑 버블 브러쉬에만 별도로 옵션을 추가하는게 나을듯 싶음...

**Comment by seogi1004** [comment]
color 옵션은 아래와 같이 사용할 수 있습니다.
```
brush : {
                type : 'bubble',
                //colors : [ "red", "blue" ],
                target : [ 'name', 'value'],
                min : 1,
                max : 50,
                color : function(value, key) {
                    if(value > 5) {
                        return "red";
                    }

                    return "blue";
                }
            }
```

**Comment by jinammin** [comment]
빠른 조치에 감사드립니다. ^^
다만, 현재 제가 사용하고 있고, 요청드렸던 것은 Bar Chart에 관해서인데
이 코드가 Bubble Chart가 아닌 Bar Chart에도 동일하게 적용되는 것인지요?

**Comment by seogi1004** [comment]
@jinammin 변경 사항이 있을 것 같네요. 다시 가이드해드리겠습니다.

**Comment by seogi1004** [comment]
color 옵션을 제거하고, 기존의 colors 옵션으로 대체하였습니다.
colors 옵션을 사용하는 방법은 아래와 같습니다.

```javascript
colors : [ "rgb1", "rgb2" ] // 또는
colors : [ 0, 1 ] // 테마에 설정된 컬러 인덱스
colors : function(data) {
    return "rgb1";
}
```

관련 샘플은 아래 링크를 참고해주세요.
http://seogi1004.github.io/jui/res/chartplay/index.html#range_scatter_zoom.js

아직 scatter와 bubble만 적용했습니다.
다른 브러쉬도 적용되면 댓글로 알려드리겠습니다.

**Comment by jinammin** [comment]
감사합니다!
colors 옵션을 활용하며 드는 궁금증이 있는데, 테마에 설정된 컬러 인덱스 외에 다른 컬러들을 사용할 수 있는지요? 예를들어 #000000 처럼 컬러코드를 활용하여 원하는 색을 표현할 수 있다면 참 좋을텐데요.

**Comment by easylogic** [comment]
colors 옵션은 중복으로 사용 가능합니다. 


```javascript
colors : [ "mycolor", 5, "#bbbbbb"] 
```

참고하세요 ~

**Comment by jinammin** [comment]
몰랐던 정보네요! 감사합니다^^

**Comment by seogi1004** [comment]
@jinammin 덕분에 애매했던 브러쉬 컬러에 대해 정리를 할 수 있었네요. ㅠㅠㅋㅋ
일단 colors 옵션은 배열 또는 콜백 함수로만 사용할 수 있고, 관련해서는 아래 링크를 참고하시는게 좋겠네요. 일단 자주 사용되는 bar와 column, scatter, bubble 브러쉬에서 사용할 수 있습니다.

http://seogi1004.github.io/jui/res/chartplay/index.html#brush_colors_callback.js

**Comment by jinammin** [comment]
드디어 원하던대로 차트를 활용할 수 있겠네요! 정말 감사합니다! ^^ 고생 많으셨어요!
