### ISSUE TITLE
Thousands Separators 문의

### ISSUE THREAD

**Issue by kiizoo** [seogi1004/jui#280]
안녕하세요

Y축에 표시되는 숫자 1000단위마다 
콤마(쉼표)기능 Thousands Separators 포멧을 줄려면 어떻게 해야 하는지요
예 )  금액     29,600,000

**Comment by easylogic** [comment]
@kiizoo   안녕하세요.. 

jui 에서는 따로 number format 관련된 함수를 제공하지는 않습니다. 

http://openexchangerates.github.io/accounting.js/ 

이쪽 라이브러리를 써보시는건 어떨까요?

**Comment by kiizoo** [comment]
@easylogic 답변 감사합니다
말씀하신 라이브러리 활용해보겠습니다

실제 JUI로 만든 챠트화면들을 연세가 많으신 경영진, CEO 분들이 보시다보니
저런 Thousands Separators기능을 많이 요구하시네요.
실 데이터는 숫자가 엄청 크거든요

**Comment by easylogic** [comment]
@kiizoo 

실제 데이타가 많이 큰 경우는  ,(comma) 로 구분하기 보다는 

K, M, G 형태로 전체 숫자 범위로 표시해주는것도 괜찮을 수도 있습니다. 

저도 차트만들면서 이부분이 고민이 많이 되긴 하네요...

**Comment by changhwa** [comment]
@easylogic  

지나가다가... 실제데이터가 큰 경우 K, M, G가 효율적일 수 는 있으나
위에 @kiizoo  님 경우 처럼 Thousands Separators 요청하시는 경우엔 
K,M,G가 한눈에 안들어온다 라고 말할 확률이 높습니다..(실제로 많이 겪었어요 ㅠㅠ)
옵션화가 가능하면 좋을듯합니다.^^;

**Comment by easylogic** [comment]
@changhwa 좋은 말씀 감사합니다. 

숫자 표시 부분에 대해서 고민을 좀 해봐야겠네요. ^^

**Comment by kiizoo** [comment]
@changhwa   
실제 챠트를 보시는 분들은 CEO분들이여서 요구사항의 강도가 정말..너무 높네요..
반드시 그렇게 해야만 하는 상황이라서... 챠트쪽 콘트롤이 쉽지가 않네요..

**Comment by seogi1004** [comment]
@kiizoo 참고로 format 옵션의 콜백 함수로 Y축 값을 변경할 수 있습니다. 실제로 저희 회사 제품에서도 그렇게 사용 중입니다.

```
format: function(value) {
    // 구현부
    return value;
}
````

**Comment by seogi1004** [comment]
format 콜백 옵션을 사용하면 해결할 수 있는 이슈이므로 클로즈합니다.
