### ISSUE TITLE
[JUI] Scatter Chart: X축과 Y축의 상호 변환 기능

### ISSUE THREAD

**Issue by jinammin** [seogi1004/jui#282]
안녕하십니까. JUI를 유용하게 잘 활용하고 있는 사용자입니다.

Scatter Chart를 쓰는 도중에 사용자가 어떤 데이터를 나타내려고 하는지에 따라 X축과 Y축을 상호 변환할 수 있는 기능이 필요하다고 생각했습니다.
즉, 현재는 X축이 '국어', '영어', '수학'이면 Y축은 0~100점을 나타냅니다.
그러나 이를 과목 수가 추가되어도 가로로 길어지는게 아니라, 세로로 길어지도록 Y축이 '국어', '영어', '수학'이고, X축이 0~100점을 나타내도록 변경하고 싶습니다.
이에 대한 축 변환 기능이 있다면 알려주시고, 없다면 개발 요청드립니다.

언제나 고생많으십니다. 감사합니다.

**Comment by seogi1004** [comment]
일단 스카터는 x와 y축이 바뀌었을 때도 보여지게 수정을 해야합니다.
https://github.com/seogi1004/jui/issues/286

하지만 axis의 그리드는 동적으로 변경할 수 있습니다.
https://github.com/seogi1004/jui/blob/develop/sample/chart/change_grid.html

**Comment by jinammin** [comment]
다음과 같이 수정을 했는데, 값이 보이지 않는 이유는 아직 구현이 되지 않았기 때문인가요? 아니면 제가 코드 입력을 잘못한 것이기 때문인가요?

<div id="chart"></div>
<a href="javascript:changeGrid()">Change grid</a>

<script id="tpl_tooltip" type="text/template">
    <div class="tooltip tooltip-top tooltip-black">
        <div class="anchor"></div>
        <div class="message"><!= obj.dataKey !>: <!= obj.data[obj.dataKey] !></div>
    </div>
</script>

<script>
    jui.ready([ "chart.builder" ], function(chart) {

         chart("#chart", {
            width: 1200,
            height : 400,
            theme : "jennifer",
             axis : {
                 x : {
                     type : "block",
                     domain : [ '수학', '과학', '영어' ],
                     line : true
                 },
                 y : {
                     type : "range",
                     domain : [ 0, 100 ],
                     step : 10
                 },
                 data : [
                     { min: 42, avg: 65, max: 92 },
                     { min: 31, avg: 64, max: 84 },
                     { min: 58, avg: 81, max: 99 }
                 ]
             },
             series : {
                 min : { symbol : "rectangle" },
                 avg : { symbol : "circle" },
                 max : { symbol : "triangle" }
             },
             brush : {
                 type: "scatter",
                 size: 10
             },
             widget : [
                 { type : "title", text : "과목별 최대, 평균, 최소 점수 비교"},
                 { type : "tooltip" }
             ]
        });
	});


    function changeGrid() {
        var axis = c.axis(0);
        axis.updateGrid("y", {
            type : "block",
            domain : [ '수학', '과학', '영어' ],
            line : true
        });
        axis.updateGrid("x", {
            type : "range",
            domain : [ 0, 100 ]
        });
	}

</script>

**Comment by seogi1004** [comment]
@jinammin 브러쉬는 x와 y 축 스왑이 되게 구현을 해야하구요.
일단 그리드만 변경되는 것을 보여주는 샘플입니다. ㅠㅠ

**Comment by seogi1004** [comment]
develop 브랜치 다운로드 받으시구요.
아래 샘플 참고하시면 됩니다. ^^

https://github.com/seogi1004/jui/blob/develop/sample/chart/change_grid.html

**Comment by jinammin** [comment]
감사합니다. 덕분에 원하는 모습으로 화면 구성을 할 수 있게 되었네요! ^^
한가지 더 궁금한게 있는데, 지금처럼 클릭을 했을 때 축이 변하는 방식이 아니라
처음부터 축이 변환되어있게 하려면 어떻게 처리를 해야 하는건가요?

**Comment by seogi1004** [comment]
@jinammin 답변이 늦었네요. x와 y축을 바꿔서 설정하시면 됩니다!
