### ISSUE TITLE
angular js에서 JUI 차트 사용관련 문의

### ISSUE THREAD

**Issue by Kimyoungchan** [seogi1004/jui#284]
안녕하세요~
좋은 라이브러리 개발해 주셔서 감사합니다.
다름이 아니라 몇가지 질문이 있어서 글 드립니다.

angular js 이용해서 차트를 그렸다. jui chart 로 바꾸려고 하는데 몇가지 문제가 있어서 질문드립니다. 

$scope.data = [
 { weeks : $scope.labelsRetention[0], store1 : $scope.dataSource[0].totCnt1, store2 : $scope.dataSource[1].totCnt1 }
]

이런 식으로 데이터 셋을 구성해 차트를 그리는데, weeks 나 store1 같은 brush내의 target(혹은 axis내의 domain값)은 동적으로 사용 할수 없나요?

데이터 셋 구성 전에
var store1 = $scope.dataSource[0].storeNm;
위처럼 선언하면 target에서의 store1이 동적으로 바뀌는데, 데이터 셋 내의 store1같은 경우는 바뀌지가 않네요.

그리고 jui 차트를 그리는 부분이 디버깅시에는 버튼 클릭이벤트를 타고 다시 그려지고있는데, 화면에는 출력되지 않네요.. 뭔가 다른 방법이 있는건가요?

**Comment by seogi1004** [comment]
일단 도메인 값을 동적으로 설정하는 방법은 아래 링크를 참조하시면 될 것 같습니다. http://seogi1004.github.io/jui/res/chartplay/index.html#grid_set_domain3.js

**Comment by Kimyoungchan** [comment]
음 제말은 아래 처럼
라인 차트의 경우 라인의 타이틀을 동적으로 변경 할 수 있는지 하는 질문이었습니다..
예를 들면 아래 소스코드 처럼 a의 홀짝에 따라 company가 변경되도록 할 수 있는지 궁금합니다.

var chart = jui.include("chart.builder");

		var a = Math.floor(Math.random() * 10) + 1;
		var company = "";
		a % 2 == 0?  company = "apple" : company = "samsung"
		  

		chart("#lineChartTest", {
		    axis : {
		        x : {
		            type : "block",
		            domain : [ "2010", "2011", "2012", "2013" ],
		            line : true,
		            full : true
		        },
		        y : {
		            type : "range",
		            domain : function(d) {
		                return Math.max(d.company, d.microsoft, d.oracle);
		            },
		            step : 10
		        },
		        data : [
		            { company : 26.1, microsoft : 24.86, oracle : 22.08 },
		            { company : 43.83, microsoft : 25.14, oracle : 30.15 },
		            { company : 55.03, microsoft : 24, oracle : 24.88 },
		            { company : 72.95, microsoft : 25.39, oracle : 32.78 }
		        ]
		    },
		    brush : [{
		        type : "line",
		        animate : true
		    }, {
		        type : "scatter",
		        hide : true
		    }],
		    widget : [
		    	{ type : "title", text : "Line Sample" },
		    	{ type : "legend" },
		        { type : "tooltip", brush : 1 }
		    ]
		});

**Comment by seogi1004** [comment]
x축의 도메인을 배열이 아닌 "company"로 설정을 하고, 실제 데이터의 company 프로퍼티를 데이터의 인덱스의 짝수/홀수 여부에 따라 "apple" 또는 "samsung"으로 변경하시면 원하시는 결과가 나올 것 같습니다.

실은 라인의 타이틀이 무엇을 의미한지 잘 모르겠습니다.
위의 설명을 틀리다면 좀 더 자세한 설명 부탁드릴게요.

**Comment by Kimyoungchan** [comment]
제 설명이 이상했나보네요 ㅠㅠ
죄송합니다..

그림으로 설명드릴게요
아래 그림은 JUI차트 페이지에서 Line Basic부분을 캡쳐한 것 인데요.
아래의 라인들(apple, microsoft, oracle)을 동적으로 세팅 할 수 있냐는 말씀을 드리고싶었습니다..
참고 부탁드리겠습니다.

![default](https://cloud.githubusercontent.com/assets/12806382/8050793/48141950-0eae-11e5-9fa0-14ed0a161b44.png)

**Comment by easylogic** [comment]
@Kimyoungchan 

```javascript

// target  리스트 설정 
var target_list = ["apple", "oracle"];

// 특정 조건에 변경 
if (a %2 == 0) { target_list = ["samsung", "oracle"]; } 

brush : {
   type : 'line',
   target : target_list    // 생성시점에 target_list 를 넘겨줍니다. 
}

```

이런 패턴으로 하시면 될 것 같아요.

**Comment by Kimyoungchan** [comment]
음.. 문제가 발생한 소스를 보여드릴게요..


    				///////////////////////Chart START//////////////////////////////////////// 				
    				
                                var store1 = $scope.dataSource[0].storeNm;
                                var store2 = $scope.dataSource[1].storeNm;

    				var chart = jui.include("chart.builder");
    		    	
    				$scope.dataSource = [
    								  { weeks : $scope.labelsShopperRetention[0], store1 : $scope.dataSource[0].totCnt1, store2 : $scope.dataSource[1].totCnt1 },
    								  { weeks : $scope.labelsShopperRetention[1], store1 : $scope.dataSource[0].totCnt2, store2 : $scope.dataSource[1].totCnt2 },
    				                  { weeks : $scope.labelsShopperRetention[2], store1 : $scope.dataSource[0].totCnt3, store2 : $scope.dataSource[1].totCnt3 },
    				                  { weeks : $scope.labelsShopperRetention[3], store1 : $scope.dataSource[0].totCnt4, store2 : $scope.dataSource[1].totCnt4 },
    				                  { weeks : $scope.labelsShopperRetention[4], store1 : $scope.dataSource[0].totCnt5, store2 : $scope.dataSource[1].totCnt5 },
    				                  { weeks : $scope.labelsShopperRetention[5], store1 : $scope.dataSource[0].totCnt6, store2 : $scope.dataSource[1].totCnt6 }
    				              ];
    				
    				chart("#shpprRtntn-Chart", {
    				    axis : [{x : {
    				            domain : "weeks",
    				            color : 1
    				        },
    				        y : {
    				            type : "range",
    				            domain: [ 10, 50 ],
    				            step : 3,
    				            color : 1
    				        },
    				        data : $scope.dataSource
    				    }, {
    				        x : {
    				            domain : "",
    				            color : 2,
    				            orient : "top"
    				        },
    				        y : {
    				            type : "range",
    				            domain : [ 10, 50 ],
    				            step : 3,
    				            color : 2,
    				            orient : "right",
    				        },
    				        data : $scope.dataSource
    				    }],    
    				    brush : [{
    				        type : "column",
    				        target : [ store1, store2 ],
    				        colors : [ 1, 2 ],
    				        innerPadding : -40,
    				        outerPadding : 20
    				    }, {
    				        type : "line",
    				        target : [ store1, store2 ],
    				        axis : 1,
    				        colors : [ 1, 2 ],
    				        symbol : "curve"
    				    }, {
    				        type : "scatter",
    				        target : [ store1, store2 ],
    				        axis : 1,
    				        colors : [ 1, 2 ]
    				    }],
    				    widget : [
    						    	{ type : "legend", brush : [ 0 ], align : "end" }
    						    ],
    				    style : {
    				        gridAxisBorderWidth : 2,
    				        titleFontSize : "11px",
    				        titleFontWeight : "bold"
    				    }
    				});	
    				///////////////////////Chart END//////////////////////////////////////////

위에 보시면 store1, store2가 dataSource란 배열에서 가져오는데, 이 배열이 사용자의 선택 여부에 따라 값이 달라집니다. 
예를들면 store1을 삼성으로 선택하면 삼성에 관련된 정보가 dataSource에 들어가게 되고, 엘지를 선택하면 엘지에 관련된 정보가 dataSource에 들어가게 됩니다.

근데 변수처리된 store1, store2가  { weeks : $scope.labelsShopperRetention[0], store1 : $scope.dataSource[0].totCnt1, store2 : $scope.dataSource[1].totCnt1 }
이부분의 store1과 store2에서 변수가 세팅이 되는 게 아니라 store1, store2라는 텍스트가 세팅이되고,     brush : [{
    				        type : "line",
    				        target : [ store1, store2 ],
    				        axis : 1,
    				        colors : [ 1, 2 ],
    				        symbol : "curve"
    				    }, {
위 brush 부분에서는 store1, store2가 위에 선언한 변수로 처리가 되어 차트가 그려지지 않고 있는 문제를 말씀드리고 싶었습니다 ㅠㅠ

dataSource에 store1이란 변수를 선언하지 않고 바로 $scope.dataSource[0].storeNm 값을 넣어 세팅하면 신텍스 에러가 나서 위같은 방법으로 해 보았는데, 잘 되지 않네요..

디버깅해보면 store1, store2 변수에는 제가 의도한 값이 잘 들어가는데, dataSource에있는 store1, store2 값에는 변수가 들어가지않고 그대로 store1, store2값이 스트링이로 박히는 것 같습니다.

설명이 더 필요하다면 말씀해주세요 ㅠㅠ
어디 물어볼 곳이 마땅치 않아 이렇게 부탁드립니다..

**Comment by easylogic** [comment]
일단 차트 설정의 경우  최초는 설정만 됩니다. 

이후에 업데이트 하는 부분에 대해서는 updateBrush 메소드를 사용하실 수 있어요. 

http://seogi1004.github.io/jui/res/chartplay/index.html#update_brush.js

여기 보시면 5초 뒤에 브러쉬를 바꿉니다. 

이런 방식으로 

chart.updateBrush 메소드를 사용해서 이벤트가 일어날때마다(또는 데이타가 셋팅될때마다) 
target 에 들어가는 배열을 바꿔주시면 될 것 같아요.

**Comment by Kimyoungchan** [comment]
{ weeks : $scope.labelsShopperRetention[0], store1 : $scope.dataSource[0].totCnt1, store2 : $scope.dataSource[1].totCnt1 }
데이터 넣는 이 부분에서 store1, store2 값들은 동적으로 처리 할 수 없다는 말씀이신거죠? ㅠ
위처럼 적용해보니 되긴하는데 브러쉬 바꾸는 시간을 0으로해도 깜빡 거리는게 눈에 영 거슬리네요 ㅎㅎ
답변 감사드립니다!!

**Comment by Kimyoungchan** [comment]
감사합니다~
