### ISSUE TITLE
Scatter 브러쉬, horizontal 타입도 추가

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#286]
세로가 아닌 가로 형태일 때도 동작이 되게 수정
바와 컬럼은 별도의 브러쉬지만 이건 옵션으로 해도 될 것 같음...

**Comment by easylogic** [comment]
루프 도는 우선순위 개념을 두는것도 좋겠음. 

지금은 x 축 기준으로 돌게 되어 있는데. 

loop : 'y' 하면 

y 축으로 돌기

**Comment by easylogic** [comment]
이거 설정 할 수 있으면 bar column 을 나눌필요가 없...........

**Comment by seogi1004** [comment]
=ㅁ= 나도 나누고싶지 않넹... 어케해야할까?

**Comment by seogi1004** [comment]
브러쉬 코어의 getXY, getStackXY 메소드를 수정했음...
y축이 range일 경우 그대로하고, x축이 range일 경우 x랑 y를 바꿨음...
