### ISSUE TITLE
date, dateblock 그리드 개선

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#288]
date, dateblock 그리드 개선 좀 합시다.

기존
domain: [ new Date(), new Date() ]
step: [ time.hours, 1 ]

~~추가
domain: [ "2015/06/06", "2015/06/07" ]
step: [ 1000 * 60 * 60, 1 ]~~

추가2 (현재 ~ 이전시간)
domain: -1000 * 60 * 5
step: 1000 * 60 * 60

**Comment by seogi1004** [comment]
step은 그냥 배열을 제거하는게 좋을듯...
step: time.hours * 5 이런식이 나을듯 한데?

**Comment by seogi1004** [comment]
참고로 dateblock은 데이터가 없어도 x축이 그려지는데, date는 그려지지 않음...
이거 진짜 날잡아서 제대로 고쳐야할 듯... 많이 사용하는거라 ㅠㅠ

**Comment by seogi1004** [comment]
block/dateblock, full 옵션이 true일때와 false일때 rangeBand 크기가 다름;;;
full로 사용할 수가없음...

**Comment by seogi1004** [comment]
@easylogic develop.grid 브랜치 생성했음...
그리드 관련해서 여기서 수정하는게 좋을듯 싶소...

**Comment by easylogic** [comment]
* date 그리드에 data 속성이 없을 때 안그려짐 
* step 에 interval 추가 (ms 단위)
* date, dateblock 도메인 숫자일경이 현재 시점으로  그 시점까지 적용.

**Comment by seogi1004** [comment]
이거 어찌되고있음??

**Comment by easylogic** [comment]
기본 옵션 

```javascript 
x : {
    type : 'date',
    interval : 1 * 1000 * 60 * 60   // ms 단위 , 예는 1시간 
}
```

리얼타임 옵션 (평소에 쓸일이 거의 없을 것으로 예상하나)  

```javascript 
x : {
    type : 'date', 
    interval : 1 
    intervalType : "hours"     // 시간 단위를 적어줌. 
} 
```

date, dateblock 모두 동일하게 동작합니다.

**Comment by easylogic** [comment]
develop 브랜치 업데이트 하세요

**Comment by seogi1004** [comment]
intervalType을 리얼타임에서만 사용하므로 이름을 realtime으로 변경하고...
realtime에 intervalType을 넣도록 일단 수정했음...

**Comment by seogi1004** [comment]
@easylogic dateblock은 버그가 있었음... 일단 내가 수정함...
테스트도 안하고 대충 수정해서 develop에 푸시해버리면 메뉴얼 사이트에 적용을 못하오...
그래서 별도로 브랜치를 만들어놨는데, 이게 뭐임 ㅠㅠ

**Comment by easylogic** [comment]
테스트 해보고 말해주삼.

**Comment by seogi1004** [comment]
그라데이션일 경우, 문제가 바깥에 그려짐 ㅠㅠ
http://localhost:63342/jui.site/res/chartplay/index.html#grid_dashed_gradient.js

**Comment by seogi1004** [comment]
dateblock은 적용안됬음?

**Comment by easylogic** [comment]
이슈 에 localhost 는 안됨.

**Comment by seogi1004** [comment]
차트플레이에서 보면되잖소 -ㅁ-;

**Comment by seogi1004** [comment]
@easylogic date 그리드, line 옵션 이상하게 되는 것만 수정되면 클로즈하겠음...

**Comment by seogi1004** [comment]
grid core, date, scale utility 롤백 했음
