### ISSUE TITLE
[JUI] chart Data 관련 질문

### ISSUE THREAD

**Issue by Kimyoungchan** [seogi1004/jui#291]
안녕하세요 JUI Chart 사용자 입니다.
한가지 질문이 있어 글 올립니다.
데이터가 계속 바뀌는경우 차트가 새로 고침이 되지 않는데(콘솔을 확인하면 데이터는 변경되어 있습니다.), 데이터가 바뀔때 차트를 다시 그리게 할 수 있는 방법이 있나요?

예를들면 
```javascript
var data= [
                {b : 123, c: 456, d: 678}
                ]
```
라는 데이터가 있을때, 버튼을 클릭하면 
```javascript
var data= [
                {b : 321, c: 453, d: 534}
                ]
```
이런 식으로 다른 데이터가 들어와 차트를 그리고 싶은데,
콘솔을 확인하면 데이터는 변경이 되어있는데 차트는 다시 그려지지 않고있습니다.
확인 부탁드리겠습니다.

**Comment by easylogic** [comment]
아래 구문 실행하면 렌더링을 다시 합니다. 

data 속성은 최초 설정만 하기 때문에 아래 함수로 업데이트 해줘야합니다. 

```javascript
chart.axis(0).update(data);

```
