### ISSUE TITLE
[JUI] 'drag' widget 문의.

### ISSUE THREAD

**Issue by RyuChungHwan** [seogi1004/jui#292]
JUI 차트를 사용중입니다.

scatterpath에서 drag해서 데이터를 선택하는 위젯이 추가 되어 있다는 것을 보았는데요.

사용을 어떻게 해해야 하는지.. 잘 이해가 안됩니다. 

widget : [
		        {
			        type : "drag",
			        ??????
			        ?????

	    ]

example 코드가 있으면 부탁드리겠습니다.

**Comment by easylogic** [comment]
현재 drag 위젯은 따로 없습니다. 

drag 를 할 수 있는 예제는 zoom 위젯이 있습니다. 

이걸 말씀 하시는건가요? 

http://seogi1004.github.io/jui/res/chartplay/index.html#candlestick_zoom.js

**Comment by RyuChungHwan** [comment]
음.. 제가 궁금한것은 
jennifer4  or jennifer5의 main realtime dashboard의 xview 차트처럼 무수히 많이 찍힌 scatter chart에서 
마우스로  drag했을시 그 drag한 영역이 표시되면서  x,y의 범위를 구하는 방법이 없을까 하는것입니다.

**Comment by easylogic** [comment]
@RyuChungHwan 

jennifer 에 있는 기능과 같은 drag 위젯은 아직 없습니다. 
이쪽은 따로 구현해야할 것 같습니다. 

일단 이슈로 등록하고 어떻게 진행할지는 추가로 논의를 해봐야할 것 같네요.

**Comment by RyuChungHwan** [comment]
넵 알겠습니다. 답변주셔서 감사합니다.

**Comment by easylogic** [comment]
#294 여기서 계속 논의할게요.. 

이 이슈는 닫습니다.

**Comment by seogi1004** [comment]
릴리즈 전이기 때문에 develop 브랜치를 다운로드 받아주시고...
아래 링크를 참고해주세요. ^^;

http://seogi1004.github.io/jui/res/chartplay/index.html#range_scatter_dragselect.js
