### ISSUE TITLE
implements drag widget 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#294]
zoom 위젯과 비슷한 drag 위젯이 필요합니다. 

drag 위젯은  x, y 전체에 대한 부분 값을 설정할 수 있어야 합니다. 

```javascript 
widget : {
    type : 'drag' 
}
```

drag 를 하면 선택 영역이 나오고 x, y 의 부분을 다시 렌더링 합니다.

**Comment by seogi1004** [comment]
http://seogi1004.github.io/jui/res/chartplay/index.html#range_scatter_dragselect.js

**Comment by seogi1004** [comment]
콜백으로 받는 데이터 타입 옵션으로 추가하기
(ps: 진호형 천재!)

**Comment by seogi1004** [comment]
dataType 옵션을 "list"로 하면, 이벤트로 받는 데이터가 드래그 영역 안의 데이터가 된다.
하지만 "area"로 설정한다면 시작과 끝 x와 y에 대한 값을 이벤트로 받을 수 있다.
