### ISSUE TITLE
Scatter 브러쉬, 데이터 상태에 따른 색깔 설정 옵션 추가

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#295]

**Comment by easylogic** [comment]
#279 이 이슈가 해결되면 같이 해결될지도 ~

**Comment by seogi1004** [comment]
@easylogic 저거 고민을 해보겠음~ ㅋㅋ 이 이슈 닫아야겠네!

**Comment by seogi1004** [comment]
@easylogic 막상 구현하려고보니 브러쉬의 this.color에 targetIndex만 넘기네...
이거 구현하려면 전체 브러쉬 다 고쳐야됨...
그냥 스카터랑 버블 브러쉬에만 별도로 옵션을 추가하는게 나을듯 싶음...

**Comment by easylogic** [comment]
그냥 color 에 옵션 하나 주는게 낫지 않음 ?

**Comment by seogi1004** [comment]
color 옵션을 별도로 만들었고, 일단 scatter랑 bubble만 바꿨음...
