### ISSUE TITLE
Bar, Column 고정 크기 옵션 추가

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#296]
고정 크기 옵션을 사용하면, outerPadding은 해야할 듯...

**Comment by easylogic** [comment]
고정크기라는건  %  형태로 가는건가?

**Comment by easylogic** [comment]
```javascript
{
  type : 'bar',
  outerPadding : 10    // 이렇게 하면 outerPadding 이 고정인데 말이지  
}
```

어떤식의 차트가 필요한거임 ? 

실제 bar 가 고정이 될려면 흠 bar 넢이에 대한 값을 따로 줘야할 듯 한데. 

옵션 하나 추가해야할 듯

**Comment by seogi1004** [comment]
outerPadding은 고정이 아님 ㅠㅠ
좌우 패딩 값을 rangeBand에서 제거하는거라 가변적임 ㅠㅠ

**Comment by seogi1004** [comment]
bar, stackbar, fullstackbar, column, stackcolumn, fullstackcolumn 브러쉬에 size 옵션 추가했음...
size 옵션을 사용하면 outerPadding은 무시되고, size와 innerPadding만 적용됨...
