### ISSUE TITLE
차트 series 옵션 제거하는 방안

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#298]
샘플을 만들면서 느낀건데, 시리즈를 쓸 경우가 거의 없네...
이럴거면 차라리 제거하는게 좋을 것 같은데...
어떻게 생각하오?

**Comment by easylogic** [comment]
series 가 이름 때문에 쓰게 된건데..    
사실 데이타 구성하기에 따라 전혀 필요없을지도 모르지..

**Comment by seogi1004** [comment]
시리즈를 뺍시다!

**Comment by easylogic** [comment]
어짜피 color 새로 만들 수 있으니. 

그리고 format 으로 텍스트 바꿀 수 있으니 

시리즈 빼도 될 듯 

뺍시다.

**Comment by seogi1004** [comment]
series 옵션 제거에 따른 text 설정을 위한 옵션이 필요한 브러쉬/위젯
 * pie, scatter, legend, tooltip
