### ISSUE TITLE
 scatter 브러쉬 size 콜백 옵션 

### ISSUE THREAD

**Issue by myjet114** [seogi1004/jui#311]
Scatter 브러쉬는 hoverSync 옵션이 true이면 마우스 오버시 모든 타겟이 오버 효과가 발생되지만
scatter 의 사이즈도 같이 커지게 할수 없나요?

**Comment by seogi1004** [comment]
차트의 style 옵션에 scatterBorderWidth 값을 3 정도 줘보세요!
