### ISSUE TITLE
Grid, Brush, Widget에 사용되는 format 옵션 콜백 매개변수 정리

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#325]
그리드는 value, index
툴팁 위젯은 key, value 형태로 매개변수를 넘긴다.

아무래도 비슷한 룰로 다시 정하는게 좋을 것 같음

**Comment by easylogic** [comment]
이렇게 하는 것도 좋을 듯 
```javascript
function(key, value, index) { } 
```

**Comment by seogi1004** [comment]
레거시 발생 ㅠ_ㅠ;
첫번째 파라메터는 데이터를 두번째는 키를 넘기도록 수정했음...
값은 보내지 않음 ㅠㅠ
