### ISSUE TITLE
ie9에서 tooltip의 메시지 reset 없이 append 되는 현상 확인 부탁드립니다.

### ISSUE THREAD

**Issue by capscharisma** [seogi1004/jui#336]
크롬에서는 tooltip으로 마우스over 했을때 해당 name이랑 key값을 잘 가져오는데 ie에서는 name이랑 key가 계속 append 되는 현상이 있는데 이게 jui.js에 setTextInTooltip(targets) 요기에서 text를 넣을때 ie에서 무언가 reset을 안하고 append 되어 tooltip이 길어지는 현상은 어떻게 해야 해결될까요?? 계속 해당 jui.js를 고치고 찍어보고 하는데 해당 객체 속성이나 메소드를 잘 몰라서 잘 안되네요. chart play도 동일하더라구요^^;;

**Comment by seogi1004** [comment]
답변이 너무 늦었네요. 확인해보겠습니다.

**Comment by seogi1004** [comment]
수정되었습니다. 아직 릴리즈 전이니 develop 브랜치 체크아웃 받아서 확인해주세요. ^^
