### ISSUE TITLE
Full 3D 지원을 위한 사전 작업

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#339]
일단 z 그리드 옵션 만들어야 할듯 -ㅁ-ㅋ

**Comment by easylogic** [comment]
z 옵션 추가하고 

기존 그리드는 똑같이 설정하고 

옵션은 hide 가 기본이 되도록 할꺼임. 

그럼 무조건 안 보이니깐.

**Comment by seogi1004** [comment]
옵션 디폴트 값으로 hide true주면되긔

**Comment by easylogic** [comment]
이거 막상 샘플을 만들려고 하니 

치명적인 문제가 있군. ㅡㅡ; 

일단 x, y 는  가로, 세로를 기준으로 픽셀을 정의 하는데. 

z 는 없음 ㅡㅡ; 

그렇게 할 수가.. 

대상이 명확하지 않아. 

z 는 전혀 다른 형태로 다시 만들어야할 듯. 

```javascript

z : {
    type : 'range', 
    domain : [0, 1000],
    range : [0, 500]     // 실제 화면 크기 대응 
}
```

애매하네 이건 카메라랑 퍼스펙티브랑 같이 들어가야 할 듯 한데.
