### ISSUE TITLE
format , colors 의 함수 처리시 데이터가 두번 콜 되는 현상

### ISSUE THREAD

**Issue by javapark** [seogi1004/jui#343]
안녕하세요. jui 를 잘 사용하고 있는 유저중 한명입니다.

다름이 아니고 아래의 옵션등에 
axis.y.format
brush.colors

함수를 지정하여 포멧을 변경하거나 색을 변경하려고 하는데
원치않게 두번씩 호출되는 현상이 발생하였습니다.

테스트한 차트는 컬럼차트이고 데이터가 5개인데 
함수안에서 로그를 찍어보면 10번이 나오는 현상이 발생하였습니다.

혹시 알고 있는 버그인지 아니면 제가 잘 못 설정한 것인지 문의를 드립니다.

**Comment by easylogic** [comment]
혹시 brush 에서 target 을 몇개로 지정하셨나요? 

target 이 없으면 전체 필드를 대상으로 하기 때문에 

row * target 수  만큼 찍히기 때문에 많이 나올 수는 있습니다.

**Comment by javapark** [comment]
Target을 하나 지정해도 두개호출이 되네요..

**Comment by easylogic** [comment]
혹시 사용하신 샘플 코드를 조금 올려주실 수 있으신가요?

**Comment by javapark** [comment]
![20150820_132346_302-1](https://cloud.githubusercontent.com/assets/288315/9375701/33920b4e-473f-11e5-8e1e-ce07c460eee1.jpg)

**Comment by easylogic** [comment]
혹시 차트 생성한 다음에 

.render() 함수 호출하시나요?

**Comment by easylogic** [comment]
차트 객체 생성할때 기본적으로 한번 render 가 되는데 그 시점에 render 를 다시 하시면 2번씩 나올 수도 있습니다.

**Comment by javapark** [comment]
render() 함수도 따로 호출하고 있지는 않습니다.  이상히네요...

**Comment by javapark** [comment]
![20150820_162853_745](https://cloud.githubusercontent.com/assets/288315/9377982/9a1d4126-4758-11e5-829c-67873a3adc4d.jpg)

**Comment by javapark** [comment]
![20150820_162957_452](https://cloud.githubusercontent.com/assets/288315/9377995/ba8050f2-4758-11e5-823b-7d195f0b8c0c.jpg)

**Comment by javapark** [comment]
확인부탁드립니다.. 위의 상황에서도 10번 colors 가 호출됩니다

**Comment by javapark** [comment]
코드상에는 문제가 없었습니다.
화면이 리사이즈 되면서 render 호출이 한번 더 일어 났습니다.
신경 써주셔서 감사드리고 이슈는 클로즈 하겠습니다
