### ISSUE TITLE
colors 에 function 지정시

### ISSUE THREAD

**Issue by javapark** [seogi1004/jui#344]
제목과 같이 color 에 function 을 이용하여 랜덤 색상을 지정하였습니다.
물론 처음에는 랜덤한 색상이 지정되었는데 문제는 윈도우를 리사이즈 할때마다
colors 함수가 호출되어 다른 색으로 변경되는 경우가 발생하였습니다.

의도하신 결과인지 아니면 이를 막을 방법이 있는지 알고 싶습니다~~~

**Comment by easylogic** [comment]
만약에 처음에 지정한 랜덤한 색상을 유지하고 싶으시면  

랜덤한 값을 배열로 미리 만들어 두시는건 어떨까요? 


```javascript

function getRandom() {
    return ['red', .... ]; // color code list 
}

var random_colors = getRandom();

brush : {
    color : randon_colors 
}
```

형태로 지정이 되면 초최 설정이 function 의해서 변하지 않습니다. 

일단 colors 에 function 을 주는건 매번 render 시점에 적용되는 부분이라 
현재로서는 막을 방법이 없습니다.

**Comment by javapark** [comment]
네... 알겠습니다~~~
