### ISSUE TITLE
도넛챠트에서 1개항목이 100%인 경우 챠트가 안나오는 현상

### ISSUE THREAD

**Issue by ffanlandboss** [seogi1004/jui#347]
제목그대로입니다. 

http://seogi1004.github.io/jui/res/chartplay/index.html#donut.js
샘플페이지에서도 아래처럼 data를 1개만 두면 화면이 안나옵니다.
반드시 2개항목 이상이여야 되는지요.. 

var chart = jui.include("chart.builder");
var names = {
    ie: "IE",
    ff: "Fire Fox",
    chrome: "Chrome",
    safari: "Safari",
    other: "Others"
};

chart("#chart-content", {
    padding : 150,
    axis : {
        data : [
            { ie : 70 }
        ]
    },
    brush : {
        type : "donut",
        showText : true,
        format : function(k, v) {
            return names[k] + ": " + v;
        }
    },
    widget : [{
        type : "title",
        text : "Donut Sample"
    }, {
        type : "tooltip",
        orient : "left",
        format : function(data, k) {
            return {
                key: names[k],
                value: data[k]
            }
        }
    }, {
        type : "legend",
        format : function(k) {
            return names[k];
        }
    }]
});

**Comment by easylogic** [comment]
버그 인것 같습니다. 최대한 빨리 수정해드릴게요 ~

**Comment by easylogic** [comment]
develop 브랜치에 적용하였습니다.

**Comment by ffanlandboss** [comment]
감사합니다. ^^
