### ISSUE TITLE
안녕하세요 덕분에 감사히 잘 사용하고 있습니다. 

### ISSUE THREAD

**Issue by ahacross** [seogi1004/jui#349]
table에서 표시를 할때 

\<kakao\> 안녕하세요 <-- 이런 데이터를 
안녕하세요 이렇게 태그를 없애고 표시합니다. 

어떻게 해야 없애지 않고 다 표시할까요?

![image](https://cloud.githubusercontent.com/assets/1546934/9680725/e0ab2aae-5333-11e5-9ebb-2eef9d11540e.png)

이미지 보시면 전 '\<kakao\>다오' 라고 설정하고 update 하였으나 표시는 '다오'만 되고 있습니다. 
태그도 다 출력되게 하고 싶은데 어떻게 해야 할까요? 

다시 한번 감사드리며 수고하세요~~ ^^

**Comment by hhgyu** [comment]
escape 함수로 감싸시면 되지않을까요?

**Comment by ahacross** [comment]
![image](https://cloud.githubusercontent.com/assets/1546934/9708575/c4606c2a-5558-11e5-961a-50c9d104c6cf.png)

escape로 감싸니까 이렇게 나오네요~ 다른 해결책은 없을까요? 

template 파싱할 때 태그들을 처리하는 부분을 skip할 수 있는 방법이 없을까요?

**Comment by easylogic** [comment]
단순히 태그 문자열이 보여야하는거면 

```javascript
var 값 = "문자열".replace(/</g, "&lt;").replace(/>/g, "&gt;");    

```

형태로 값을 넣어보세요.

**Comment by ahacross** [comment]
감사합니다~ ^^  
알려주신대로 해결했어요~~ ^^
