### ISSUE TITLE
[신규] 스위치 컴포넌트 개발

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#35]
심플한 스위치 한번 만들어봅시다.
http://dev.axisj.com/samples/AXInput/Switch.html

**Comment by easylogic** [comment]
http://store.jui.io/view.php?id=56205f4794976c577c4dec7e 

위의 형태로 구현할 예정 
![image](https://cloud.githubusercontent.com/assets/591983/10714609/f3814734-7b39-11e5-8c23-eabbaaeeeaa2.png)

**Comment by easylogic** [comment]
구현 완료. 

http://seogi1004.github.io/jui/res/uiplay/index.html#switch_1 참고
