### ISSUE TITLE
xtable 에서 scrollHeight 를 설정할 수 있는 방법이 없음. 

### ISSUE THREAD

**Issue by easylogic** [seogi1004/jui#352]
```
height() 
```

함수의 경우 buffer 모드에 따라 동작하지 않기 때문에 s-pages 모드에서는 사용할 수가 없음.

**Comment by yuhwkim** [comment]
xtable 에서도 scrollHeight 설정 가능한데요

초기 테이블 높이값 말씀하시는 건지요. 디버깅해보시면 max-height 걸려있을 수 도 있습니다.

**Comment by seogi1004** [comment]
scrollHeight 메소드 있음!
