### ISSUE TITLE
Axis의 get으로 값을 가져올 때의 문제점

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#358]
originAxis가 아닌 cloneAxis로 값을 가져오기 때문에...
차후에 해당 axis값이 변경되었을 때, origin만 변경이되서 값을 못가져 오는 경우가 발생함...

get할때, origin과 clone둘다 하던지...
아니면 변경시 clone을 갱신해주든지...

**Comment by easylogic** [comment]
updateGrid 할 때 둘 다 변경 하는 형태로 수정.
