### ISSUE TITLE
pie chart legend 짤림 이슈

### ISSUE THREAD

**Issue by sorac** [seogi1004/jui#360]
안녕하세요. 제니퍼UI 홈페이지에도 글 올린 적이 있었는데
정식으로 이슈 등록하려고 깃허브에도 왔습니다~

pie chart를 이용중입니다.
legend 옵션의 orient를 bottom으로 줬을 때, 
하단에 한줄로 나오게 되는데 차트 영역의 width 보다 데이터 양(항목 수)이 많아지면
데이터가 짤리게 됩니다.
right, left로 줬을 때 처럼 여러 줄로 나오게 하거나, 
데이터 양이 width보다 길어지면 다음 줄로 넘어가게 하고 싶습니다.  (이 방법이 좋은 것 같습니다.)

도움 부탁드립니다. 
항상 수고가 많으십니다.

**Comment by easylogic** [comment]
develop 브랜치에 적용 되었습니다. 

가로로 목록이 길어지면 대략 아래와 같이 정렬 됩니다. 

![image](https://cloud.githubusercontent.com/assets/591983/10063741/fe96c154-62ab-11e5-9171-162777aa5587.png)

**Comment by sorac** [comment]
감사합니다 덕분에 잘 쓸 수 있을 것 같습니다.
빠른 반응에 감동받았습니다~~ㅎㅎ

**Comment by easylogic** [comment]
좀 더 일찍 지원해야 했었는데 이제서야 해서 죄송하네요. 앞으로도 많은 관심 부탁드립니다.
