### ISSUE TITLE
차트 문의 드립니다.

### ISSUE THREAD

**Issue by myon04** [seogi1004/jui#369]
basic line chart  를 이용하려고 하는데
y 축 설정 값이 1 미만의 소수 값은 화면에 표시가 안됩니다.
해결 방법이 없을까요 ?

그리고 zoom 기능을 line 차트에도 적용하고 싶은데 bar chart에만 지원되는 기능인가요?

**Comment by easylogic** [comment]
y 축 domain 을 어떻게 설정하셨는지 알 수 있을까요?

**Comment by myon04** [comment]
데이터 값은 아래와 같고요 ~
[ {  load1: '0.05' , load2: '0.05' },
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.09' , load2: '0.05'},
  {  load1: '0.1' , load2: '0.05'},
  {  load1: '0.08' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.12'},
  {  load1: '0.05' , load2: '0.09'},
  {  load1: '0.05' , load2: '0.05'},
  {  load1: '0.08' , load2: '0.05'},
  {  load1: '0.06' , load2: '0.05'},
  {  load1: '0.05' , load2: '0.05'} ]

y 축 domain 은 위의 값의 최대치로 설정했습니다.

**Comment by easylogic** [comment]
버그네요.  1 미만의 숫자를 grid 에서 정상적으로 보여주지 않습니다.

**Comment by easylogic** [comment]
버그 수정 했습니다. 

develop 브랜치에서 받아서 사용해주시면 됩니다.
