### ISSUE TITLE
colorpicker 구조 변경

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#376]
일단 less 스타일은 제거합시다.
셀렉터로 특정 태그를 설정하면 안의 내용을 컬러 그라데이션으로 채우는 정도만 해도될듯...

대신 옵션으로 색상 정하는 슬라이더와 명암? 정하는 슬라이더를 타겟할 수 있도록 하면 될듯...
완성형이 아니라 조합형으로 가는게 좋을 것 같은데?

**Comment by seogi1004** [comment]
아니면 완성형으로 가도되긴한데, 요하가 완전히 디자인을 잡아줘야함...
어떻게 할꼬?

**Comment by easylogic** [comment]
무슨 말인지 이해가 안됨? less 를 제거 하다니?
