### ISSUE TITLE
Notify Top 오류

### ISSUE THREAD

**Issue by egaoneko** [seogi1004/jui#384]
```javscript
notify_3 = notify("body", {
        position: "top",
        event: handler,
        timeout: 2000,
        padding: {
            top: 100
        },
        tpl: {
            item: $("#tpl_alarm").html()
        }
```
상단과 같이 notify에 position을 top으로 잡고 body에 띄우면 body에 있는 모든 것들이 동작을 안하네요.
이는 UI Play에서도 확인되네요.

```javascript
notify_4 = notify("#notify_target", {
        position: "top",
        timeout: 0,
        distance: 30,
        tpl: {
            item: $("#tpl_alarm").html()
        }
    });
```
위와 같이 body대신 다른 target을 전해주면 정상적으로 작동하네요.

사파리와 크롬에서 테스트해봤습니다.

**Comment by easylogic** [comment]
@egaoneko 이슈 감사합니다. 

notify 를 실행하게 되면 중간에 container  를 하나 뛰우게 되는데요.

body 에 뛰우는거라 영역을 가려버려서  이벤트가 동작을 안하는 것 같네요..

버그 같습니다. 

최대한 빨리 해결하도록 하겠습니다.

**Comment by seogi1004** [comment]
develop 브랜치에 수정되었습니다!
