### ISSUE TITLE
Full 3D 차트에서 마우스 오버값 오류

### ISSUE THREAD

**Issue by jaehong-hwang** [seogi1004/jui#387]
http://seogi1004.github.io/jui/res/chartplay/index.html#full3d_scatter.js
http://seogi1004.github.io/jui/res/chartplay/index.html#full3d_column.js
두가지 모두 가장 왼쪽의 sales값이 0이아닌 15로 출력됩니다

**Comment by seogi1004** [comment]
확인해보겠습니다. ㅠㅠ

**Comment by seogi1004** [comment]
수정했습니다. develop 브랜치에 반영되어 있습니다!
