### ISSUE TITLE
[신규] 리스트 스타일 추가

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#39]
리스트 스타일 추가해봐요.
이거 많이 쓰일듯 싶네요.

http://www.99lime.com/elements/#list-example

**Comment by easylogic** [comment]
이건 기본 스타일가지고 조정이 가능한거라  

그리고 우리도 자체 아이콘을 쓸 수 있기 때문에 

굳이 우리가 지정한 스타일 적용할 필요는 없을 듯 .. 

이것도 닫음.
