### ISSUE TITLE
[개선] Table & X-Table 스크롤 개선

### ISSUE THREAD

**Issue by seogi1004** [seogi1004/jui#58]
특정 스타일에 따라 제대로 적용되지 않는 문제를 필히 개선해야 함.

 - 참고로 ie10 미만 버전에서는 table의 scroll이 적용되지 않음.
 - 그래서 xtable의 scroll 방식으로 변경하는 것을 검토해봐야 함.

**Comment by easylogic** [comment]
이거 해줘 이거 해줘 ㅋ 스크롤이 막 지맘대로 움직이고 있어
